#!/usr/bin/env python2

from slurp import *
from lxml.builder import E
from lxml import etree
import json

data = json.load(open('data/data.json'))

doctype = ('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" '
           '"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n')

page = (
    E.html(
        E.head(
            E.meta({'http-equiv': 'Content-Type',
                    'content': 'text/html; charset=utf-8'}),
            E.title('Marvin dashboard'),
            E.link({'rel': 'stylesheet',
                    'href': 'default.css',
                    'type': 'text/css'})
        ),
        E.body(
            {'class': 'interface'},
            E.div({'class': 'header'},
                  "Home - Benchmarks - Configurations - Machines - About"),
            E.hr(),
            E.h2('Top 10 regressions'),
            E.div(
                maketop10table(data['top10'])
            ),
            E.h2('Dashboard'),
            E.div(
                makemaintable(data['main'])
            )
        )
    )
)

f = open('html/dashboard.html', 'w')
f.write(doctype + etree.tostring(page, pretty_print=True))
f.close()
